apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "muxity.fullname" . }}-config
  labels: {{- include "muxity.labels" . | nindent 4 }}
data:
  ASPNETCORE_ENVIRONMENT:    Production
  ASPNETCORE_URLS:           http://+:8080
  MongoDB__DatabaseName:     {{ .Values.config.mongo.database | quote }}
  Jwt__Issuer:               {{ .Values.config.jwt.issuer | quote }}
  Jwt__Audience:             {{ .Values.config.jwt.audience | quote }}
  Storage__Provider:         {{ .Values.config.storage.provider | quote }}
  Storage__Local__BasePath:  {{ .Values.config.storage.localBase | quote }}
  Cdn__Provider:             {{ .Values.config.cdn.provider | quote }}
  Cors__WebOrigin:           {{ .Values.config.cors.webOrigin | quote }}
  RabbitMQ__Host:            {{ include "muxity.rabbitmqHost" . | quote }}
  RabbitMQ__Port:            "5672"
  RabbitMQ__Username:        {{ .Values.rabbitmq.auth.username | quote }}
  RabbitMQ__TranscodeQueue:  transcode_jobs
