apiVersion: v1
kind: Secret
metadata:
  name: {{ include "muxity.fullname" . }}-secrets
  labels: {{- include "muxity.labels" . | nindent 4 }}
type: Opaque
stringData:
  JWT_SECRET:                 {{ .Values.secrets.jwtSecret | quote }}
  OIDC_GOOGLE_CLIENT_ID:      {{ .Values.secrets.oidcGoogleClientId | quote }}
  OIDC_MICROSOFT_CLIENT_ID:   {{ .Values.secrets.oidcMicrosoftClientId | quote }}
  S3_ACCESS_KEY:              {{ .Values.secrets.s3AccessKeyId | quote }}
  S3_SECRET_KEY:              {{ .Values.secrets.s3SecretAccessKey | quote }}
  CLOUDFRONT_KEYPAIR_ID:      {{ .Values.secrets.cloudfrontKeyPairId | quote }}
  CLOUDFLARE_SIGNING_SECRET:  {{ .Values.secrets.cloudflareSigningSecret | quote }}
  MONGO_CONNECTION:           {{ include "muxity.mongoConnection" . | quote }}
  RABBITMQ_PASSWORD:          {{ .Values.rabbitmq.auth.password | quote }}
