apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "muxity.fullname" . }}-streaming
  labels:
    {{- include "muxity.labels" . | nindent 4 }}
    app.kubernetes.io/component: streaming
spec:
  replicas: {{ .Values.streaming.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "muxity.fullname" . }}-streaming
  template:
    metadata:
      labels:
        app: {{ include "muxity.fullname" . }}-streaming
    spec:
      containers:
        - name: streaming
          image: "{{ .Values.streaming.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:  { name: "{{ include "muxity.fullname" . }}-config" }
            - secretRef:     { name: "{{ include "muxity.fullname" . }}-secrets" }
          env:
            - name: MongoDB__ConnectionString
              valueFrom:
                secretKeyRef:
                  name: {{ include "muxity.fullname" . }}-secrets
                  key: MONGO_CONNECTION
            - name: Jwt__Secret
              valueFrom:
                secretKeyRef:
                  name: {{ include "muxity.fullname" . }}-secrets
                  key: JWT_SECRET
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - name: storage
              mountPath: {{ .Values.config.storage.localBase }}
              readOnly: true
          {{- end }}
          resources: {{- toYaml .Values.streaming.resources | nindent 12 }}
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 10
            periodSeconds:       15
          readinessProbe:
            httpGet: { path: /health/ready, port: 8080 }
            initialDelaySeconds: 5
            periodSeconds:       10
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: {{ include "muxity.fullname" . }}-storage
      {{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "muxity.fullname" . }}-streaming
  labels:
    {{- include "muxity.labels" . | nindent 4 }}
    app.kubernetes.io/component: streaming
spec:
  selector:
    app: {{ include "muxity.fullname" . }}-streaming
  ports:
    - port: 80
      targetPort: 8080
